// @vitest-environment node
import { describe, expect, it } from "vitest";
import { MockDataProvider, MOCK_INITIATIVE_SLUGS } from "./mock-provider";
import type { InitiativeDetail } from "./dto";

/**
 * Provider parity — lifecycle invariants both providers must satisfy.
 *
 * WHY THIS FILE EXISTS. The mock provider and the DB provider are required
 * to be shape-identical, and they are. They were NOT content-identical: the
 * mock synthesized a full set of pending reviews and controls for every
 * initiative regardless of lifecycle state, while the DB provider returns
 * what the database actually holds — and review rows are only written by
 * triage(), effective controls only by decide().
 *
 * That divergence is not cosmetic. It is why the blockers-rail bug
 * (an un-triaged, Critical-tier initiative being told "all required reviews
 * signed and controls met") survived a green 1022-test suite: the only test
 * for that component built its fixture from the MOCK provider, where the
 * failing state was unreachable. The suite could not see the path production
 * renders. docs/production-readiness.md §2.2.
 *
 * These are the rules the real system enforces, asserted against the mock so
 * a UI test that sources fixtures from it reproduces production states:
 *
 *   1. Pre-triage states (intake_draft, submitted) have NO review rows —
 *      triage() is what creates them.
 *   2. An initiative with no deployment has NO effective controls —
 *      generateEffectiveControlsInTx() attaches them to a deployment.
 *   3. domainsSigned never exceeds domainsRequired.
 *   4. A signed review carries a signedAt and a reviewer; a pending one
 *      carries neither.
 */

const provider = new MockDataProvider();

const PRE_TRIAGE = new Set(["intake_draft", "submitted"]);

// Effective controls are generated by decide() on approve / conditionally-
// approve, and by triage()'s fast-lane branch — NOT by deployment. So
// `conditionally_approved` legitimately carries controls before anything is
// deployed, while every state at or before in_review, and `rejected` (whose
// decision generates none), must carry none.
const PRE_DECISION = new Set([
  "intake_draft",
  "submitted",
  "triaged",
  "in_review",
  "rejected",
]);

async function allDetails(): Promise<InitiativeDetail[]> {
  const details = await Promise.all(
    MOCK_INITIATIVE_SLUGS.map((slug) => provider.getInitiativeDetail(slug)),
  );
  return details.filter((d): d is InitiativeDetail => d !== null);
}

describe("mock provider honours the lifecycle invariants the DB enforces", () => {
  it("covers every seeded initiative", async () => {
    const details = await allDetails();
    expect(details).toHaveLength(MOCK_INITIATIVE_SLUGS.length);
  });

  it("has no review rows before triage has run", async () => {
    const offenders = (await allDetails())
      .filter((d) => PRE_TRIAGE.has(d.summary.state) && d.reviews.length > 0)
      .map((d) => `${d.summary.slug} (${d.summary.state}): ${d.reviews.length} reviews`);

    expect(offenders).toEqual([]);
  });

  it("has no effective controls before an approval decision generates them", async () => {
    const offenders = (await allDetails())
      .filter((d) => PRE_DECISION.has(d.summary.state) && d.controls.length > 0)
      .map((d) => `${d.summary.slug} (${d.summary.state}): ${d.controls.length} controls`);

    expect(offenders).toEqual([]);
  });

  it("never reports more signed reviews than required domains", async () => {
    const offenders = (await allDetails())
      .filter((d) => d.summary.domainsSigned > d.summary.domainsRequired)
      .map((d) => `${d.summary.slug}: ${d.summary.domainsSigned}/${d.summary.domainsRequired}`);

    expect(offenders).toEqual([]);
  });

  it("keeps review status consistent with its reviewer and signature fields", async () => {
    const offenders: string[] = [];
    for (const d of await allDetails()) {
      for (const r of d.reviews) {
        if (r.status === "signed" && (!r.signedAt || !r.reviewer)) {
          offenders.push(`${d.summary.slug}/${r.domain}: signed but missing signedAt or reviewer`);
        }
        if (r.status === "pending" && (r.signedAt || r.reviewer)) {
          offenders.push(`${d.summary.slug}/${r.domain}: pending but carries a signature/reviewer`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
